const projects = [
	{
		id: 1,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: 'https://www.google.com',
		repository: '',
	},
	{
		id: 2,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 3,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 4,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 5,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 6,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 7,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 8,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
]

export default projects
