const projects = [
	{
		id: 1,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: 'large description Ecommerce - proyecto final de estudios (Soy Henry)',
		technologies: 'HTML5, CSS3, React, Redux, Node Js, Express, PostgreSQL, Material UI, Styled Components, Javascript, Sequelize, Git',
		front: 'front technologies',
		back: 'back technologies',
		db: 'data base technologies',
		other: 'other technologies',
		page: 'https://www.google.com',
		repository: '',
	},
	{
		id: 2,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
				],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 3,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
				],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 4,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
				],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 5,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 6,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 7,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
	{
		id: 8,
		name: 'Exmine',
		images: [
			'https://res.cloudinary.com/proyectofinalhenry/image/upload/v1657747268/Portafolio/Inicio_panel_de_admin_d1cooe.png',
		],
		resume: 'Ecommerce - proyecto final de estudios (Soy Henry)',
		description: '',
		technologies: '',
		front: '',
		back: '',
		db: '',
		other: '',
		page: '',
		repository: '',
	},
]

export default projects
